/** Column-mapping presets (M1). Keys are source headers (case/space-insensitive), values Candidate fields. */
export const PRESETS: Record<string, Record<string, string>> = {
  "CV Register template": {
    "Candidate Code": "candidateCode",
    Name: "name",
    "Candidate Name": "name",
    Mobile: "mobile",
    "Mobile No": "mobile",
    "Mobile Number": "mobile",
    "Alternate Mobile": "altMobile",
    "Alt Mobile": "altMobile",
    Email: "email",
    "Email ID": "email",
    "Basic Qualification": "basicQualification",
    "Additional Qualifications": "additionalQualifications",
    "Registration Number": "registrationNumber",
    "Registration No": "registrationNumber",
    "Registration Authority": "registrationAuthority",
    "Registration Year": "registrationYear",
    "Main Category": "mainCategory",
    Category: "mainCategory",
    "Profession / Functional Head": "professionFunctionalHead",
    "Profession": "professionFunctionalHead",
    "Job Title": "jobTitle",
    "Primary Specialty": "primarySpecialty",
    "Primary Speciality": "primarySpecialty",
    "Secondary Skills": "secondarySkills",
    "Experience (Years)": "experienceYears",
    Experience: "experienceYears",
    "Current Organisation": "currentOrg",
    "Current Organization": "currentOrg",
    "Current Designation": "currentDesignation",
    "Current Location": "currentLocation",
    Location: "currentLocation",
    "Preferred Locations": "preferredLocations",
    "Preferred Location": "preferredLocations",
    "Current CTC (Lakhs)": "currentCtcLakhs",
    "Current CTC": "currentCtcLakhs",
    "Expected CTC (Lakhs)": "expectedCtcLakhs",
    "Expected CTC": "expectedCtcLakhs",
    "Notice Period (Days)": "noticePeriodDays",
    "Notice Period": "noticePeriodDays",
    "Earliest Availability": "earliestAvailabilityDate",
    "Availability Status": "availabilityStatus",
    "Shift Preference": "shiftPreference",
    "Employment Preference": "employmentPreference",
    Source: "source",
    Consent: "consentRecordStoreShare",
    "TL Remarks": "tlRemarks",
  },
  "Zoho Recruit export": {
    "First Name": "firstName",
    "Last Name": "lastName",
    "Full Name": "name",
    Mobile: "mobile",
    Phone: "altMobile",
    Email: "email",
    "Highest Qualification Held": "basicQualification",
    "Current Job Title": "jobTitle",
    "Current Employer": "currentOrg",
    "Experience in Years": "experienceYears",
    City: "currentLocation",
    "Skill Set": "secondarySkills",
    "Current Salary": "currentCtcLakhs",
    "Expected Salary": "expectedCtcLakhs",
    Source: "source",
    "Candidate Status": "tlRemarks",
  },
};

export const norm = (h: string) => h.toLowerCase().replace(/[^a-z0-9]/g, "");
